spring:
  datasource:
    url: jdbc:mysql://${TiDB_USERNAME}:${TiDB_PASSWORD}@gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/molly?sslMode=VERIFY_IDENTITY&serverTimezone=Asia/Shanghai
    username: ${TiDB_USERNAME}
    password: ${TiDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.demo.molly: info
