spring:
  application:
    name: molly

  profiles:
    active: dev

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1800s

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 2

  servlet:
    session:
      timeout: 30m
      cookie:
        name: SESSION
        http-only: true
        same-site: strict

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: h2
  reasonable: true
  support-methods-arguments: true

session:
  cache-timeout: 1800
